[package]
name = "water_db_lab"
version = "0.0.1"
edition = "2018"

[dependencies]
log = "*"
env_logger = "*"
thiserror = "*"

sqlparser = "0.9"
sled = "0.34"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"